# Generated by Django 5.2.1 on 2025-05-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
